global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'transaction_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['transaction-service:8082']
        labels:
          application: 'Transaction Service Application'
  - job_name: 'customer_service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['account-service:8081']
        labels:
          application: 'Account Service Application'
