input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if [type] == "customer-service" {
    grok {
      match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:loglevel} \[%{DATA:thread}\] %{DATA:class} - %{GREEDYDATA:message}" }
    }
    date {
      match => [ "timestamp", "ISO8601" ]
    }
  }
}

output {
  elasticsearch {
    hosts => ["${ES_HOST}:${ES_PORT}"]
    index => "myapp-%{+YYYY.MM.dd}"
    }
}